### ISSUE TITLE
请教@AutoAccess注解加到单例中的属性作用是什么？

### ISSUE THREAD

**Issue by CoderYellow** [ThirtyDegreesRay/DataAutoAccess#2]
[在OpenHub项目中的一处用法](https://github.com/ThirtyDegreesRay/OpenHub/blob/02b8de4f362f2bfb42d3bba26b4c419c1b959e6d/app/src/main/java/com/thirtydegreesray/openhub/AppData.java#L22)
```
public enum  AppData {
    INSTANCE;

    @AutoAccess(dataName = "appData_loggedUser") User loggedUser;
    @AutoAccess(dataName = "appData_authUser") AuthUser authUser;
    @AutoAccess(dataName = "appData_systemDefaultLocal") Locale systemDefaultLocal;
     ......
```

**Comment by Kurdenes21** [comment]
> [在OpenHub项目中的一处用法](https://github.com/ThirtyDegreesRay/OpenHub/blob/02b8de4f362f2bfb42d3bba26b4c419c1b959e6d/app/src/main/java/com/thirtydegreesray/openhub/AppData.java#L22)
> 
> ```
> public enum  AppData {
>     INSTANCE;
> 
>     @AutoAccess(dataName = "appData_loggedUser") User loggedUser;
>     @AutoAccess(dataName = "appData_authUser") AuthUser authUser;
>     @AutoAccess(dataName = "appData_systemDefaultLocal") Locale systemDefaultLocal;
>      ......
> ```
